
version: '0.1'

services:

  users:
    build: ./_users
    env_file:
      - ./_users/.env
    volumes:
      - ./_users:/users_root
    ports:
      - 12121:12121
    depends_on:
      - pg
      - rabbitmq
    networks:
        - rabbitmq_net

  profiles:
    build: ./_profiles
    env_file:
      - ./_profiles/.env
    volumes:
      - ./_profiles:/profiles_root
    ports:
      - 12122:12122
    depends_on:
      - pg
      - rabbitmq
    networks:
        - rabbitmq_net

  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - ./postgres:/postgresql/db

  pgadmin:
    container_name: pgadmin
    depends_on:
      - pg
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: no@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    expose:
      - '80'
    restart: always

  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/rabbitmq/durables/:/var/lib/rabbitmq/
        - ~/rabbitmq/logs/:/var/log/rabbitmq
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge